### ISSUE TITLE
[Enhancement] : `buffering_interval` variable validation doesn't allow to specify values less than 60 seconds.

### ISSUE THREAD

**Issue by plain5** [fdmsantos/terraform-aws-kinesis-firehose#7]
## Description

* Hi there :) Modifying the `buffering_interval` variable validation would be great to allow specifying values less than 60 seconds.

* From ***[documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream.html)*** :

*The `elasticsearch_configuration` object supports the following:*
* *`buffering_interval` - (Optional) Buffer incoming data for the specified period of time, in seconds between 0 to 900, before delivering it to the destination. The default value is 300s.*

**Comment by fdmsantos** [comment]
Thanks for issue. I think I'll have this ready by Monday.

**Comment by fdmsantos** [comment]
This bug fix is included in version 2.2.2. Thank you

**Comment by plain5** [comment]
* Thank you too!
