### ISSUE TITLE
[Enhancement] : Provide support for the `opensearch_configuration` object.

### ISSUE THREAD

**Issue by plain5** [fdmsantos/terraform-aws-kinesis-firehose#8]
## Description

* Hi there :) It would be great to provide support for the `opensearch_configuration` object inside `aws_kinesis_firehose_delivery_stream` resource.

* One more thing is that recently `terraform-provider-aws` got an ***[update](https://github.com/hashicorp/terraform-provider-aws/pull/35137)*** to allow specifying ***[document_id_options](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream.html#document_id_options)*** inside the `opensearch_configuration` object. This option requires at least the `5.32.0` `aws` provider version. You can also check the ***[related issue](https://github.com/hashicorp/terraform-provider-aws/issues/32064)***.

* *DocumentID type - (introduced in May, 2023) - this is the method for setting up document ID. The supported methods are Kinesis Data Firehose-generated document ID and OpenSearch Service-generated document ID. Kinesis Data Firehose-generated document ID is the default option when the document ID value is not set. OpenSearch Service-generated document ID is the recommended option because it supports write-heavy operations, including log analytics and observability, consuming fewer CPU resources at the OpenSearch Service domain and thus, resulting in improved performance.*

**Comment by fdmsantos** [comment]
Thank you for this issue. This will take more time, because have breaking changes, so i need prepare a new major version.
I'm expecting having this done until end of January.

**Comment by fdmsantos** [comment]
Some feedback about this: Opensearch_configuration block is developed and tested with DocumentID Type attribute.

Now i'm adding support for Opensearch serverless block.

I have hopes of having the new version released this month.

**Comment by fdmsantos** [comment]
This feature request is included in version 3.0.0. Thank you

**Comment by plain5** [comment]
* Thank you very much! I highly appreciate the accomplished amount of work!
