### ISSUE TITLE
Provider specified to strict aws provider major version

### ISSUE THREAD

**Issue by maordavidov** [fdmsantos/terraform-aws-kinesis-firehose#9]
Seems like the provider is strict to `~> 5.0` which is not best practice for internal modules. Since we might use other modules that will require higher versions in the future.

Is it possible to change it to `>=  5.0`?

**Comment by fdmsantos** [comment]
Hi, Thanks for this issue and suggestion.

I will change the version constraint on next version.

**Comment by fdmsantos** [comment]
This bug fix is included in version 2.2.3. Thank you
